### PR TITLE
Adding Communication

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Elbouchouki — CHANGES_REQUESTED** [review]
Everything we discussed at our last team meeting is not what you did, so please attend our meetings first.

**Comment by YacoubBen7amama** [comment]
The architecture was previously discussed during the conception phase and was marketed as completed.
 Any alterations to the architecture should be documented in Figma, as is customary. Additionally, it would be advisable to consult a dictionary for the definition of a meeting. It is unlikely that the definition includes scheduling a meeting and attending it based on personal whims. All scheduled meetings are recorded on WhatsApp, and while I have not had difficulty attending them, some individual seem to schedule and  neglect meetings based on his own mood . I regret that I am not available to participate in such behavior.

**Comment by oaymn** [comment]
- I believe discussion related to internal communications should be kept from github. Let's keep things professinal.
- The design and architecture are never definit we are always looking for more optimized and efficient solutions. Those solutions may but not necessarly lead to changes. Currently we have no changes to the latest versions but rather ideas that needed more clearence.
- There were multiple suggestions but we couldn't make such changes due to time constraints. Perhaps we would be able to do in the future.

**Comment by oaymn** [comment]
There are a lot of changes that are neither discussed nor in respect our design, such a mess cannot be merged.

**Pull request closed without merging**
